const canvas = document.getElementById("gameCanvas");
const ctx = canvas.getContext("2d");

const screens = {
  start: document.getElementById("startScreen"),
  tutorial: document.getElementById("tutorialScreen"),
  level: document.getElementById("levelScreen"),
  result: document.getElementById("resultScreen"),
  gameOver: document.getElementById("gameOverScreen"),
  pause: document.getElementById("pauseScreen"),
};

const ui = {
  clearOverlay: document.getElementById("clearOverlay"),
  finalGateOverlay: document.getElementById("finalGateOverlay"),
  finalVideoOverlay: document.getElementById("finalVideoOverlay"),
  finalVideo: document.getElementById("finalVideo"),
  playFinalVideoButton: document.getElementById("playFinalVideoButton"),
  skipFinalVideoButton: document.getElementById("skipFinalVideoButton"),
  clearText: document.getElementById("clearText"),
  pulseButton: document.getElementById("pulseButton"),
  joystick: document.getElementById("joystick"),
  joystickKnob: document.getElementById("joystickKnob"),
  soundButton: document.getElementById("soundButton"),
  pauseButton: document.getElementById("pauseButton"),
  tutorialButton: document.getElementById("tutorialButton"),
  tutorialBackButton: document.getElementById("tutorialBackButton"),
  resumeButton: document.getElementById("resumeButton"),
  restartButton: document.getElementById("restartButton"),
  levelKicker: document.getElementById("levelKicker"),
  levelTitle: document.getElementById("levelTitle"),
  levelBrief: document.getElementById("levelBrief"),
  briefGoal: document.getElementById("briefGoal"),
  briefThreat: document.getElementById("briefThreat"),
  resultTitle: document.getElementById("resultTitle"),
  resultRank: document.getElementById("resultRank"),
  resultScore: document.getElementById("resultScore"),
  resultCombo: document.getElementById("resultCombo"),
  resultLives: document.getElementById("resultLives"),
  resultTime: document.getElementById("resultTime"),
  resultComment: document.getElementById("resultComment"),
  nextButton: document.getElementById("nextButton"),
};

const hud = {
  root: document.getElementById("hud"),
  level: document.getElementById("hudLevel"),
  score: document.getElementById("hudScore"),
  goal: document.getElementById("hudGoal"),
  lives: document.getElementById("hudLives"),
  maxLives: document.getElementById("hudMaxLives"),
  points: document.getElementById("hudPoints"),
  combo: document.getElementById("hudCombo"),
  energy: document.getElementById("hudEnergy"),
  energyFill: document.getElementById("energyFill"),
  time: document.getElementById("hudTime"),
};

const levels = [
  {
    name: "晨星航道",
    brief: "收集星核，穿过第一道巡航网。",
    goal: 8,
    timeLimit: 48,
    speed: 225,
    hazardRate: 1.05,
    mineRate: 0.12,
    gateRate: 0,
    coreRate: 0.9,
    shardRate: 0.36,
    powerRate: 0.16,
    colors: ["#59d6ff", "#ffcf5a", "#8dff8a"],
    threat: "低",
  },
  {
    name: "赤环裂谷",
    brief: "裂谷会抛出高速碎片，保持连击才能拿到高评分。",
    goal: 10,
    timeLimit: 52,
    speed: 285,
    hazardRate: 1.3,
    mineRate: 0.22,
    gateRate: 0.08,
    coreRate: 0.8,
    shardRate: 0.44,
    powerRate: 0.18,
    colors: ["#ff4e80", "#ffcf5a", "#59d6ff"],
    threat: "中",
  },
  {
    name: "冰蓝环带",
    brief: "激光门开始封锁跑道，找准缺口快速穿越。",
    goal: 12,
    timeLimit: 55,
    speed: 320,
    hazardRate: 1.45,
    mineRate: 0.32,
    gateRate: 0.16,
    coreRate: 0.74,
    shardRate: 0.5,
    powerRate: 0.2,
    colors: ["#c88dff", "#59d6ff", "#8dff8a"],
    threat: "中高",
  },
  {
    name: "暗潮矿阵",
    brief: "追踪雷会缓慢锁定你，护盾道具会非常关键。",
    goal: 14,
    timeLimit: 58,
    speed: 365,
    hazardRate: 1.62,
    mineRate: 0.46,
    gateRate: 0.2,
    coreRate: 0.7,
    shardRate: 0.54,
    powerRate: 0.2,
    colors: ["#ff4e80", "#8dff8a", "#ffcf5a"],
    threat: "高",
  },
  {
    name: "终点星门",
    brief: "最终星门火力密集，脉冲时机决定通关质量。",
    goal: 16,
    timeLimit: 62,
    speed: 410,
    hazardRate: 1.82,
    mineRate: 0.56,
    gateRate: 0.26,
    coreRate: 0.66,
    shardRate: 0.58,
    powerRate: 0.22,
    colors: ["#59d6ff", "#ffcf5a", "#c88dff"],
    threat: "极高",
  },
];

const assetUrls = {
  start: "assets/optimized/bg-start.jpg",
  fail: "assets/optimized/bg-fail.jpg",
  clear: "assets/optimized/bg-clear.jpg",
  sprites: "assets/optimized/ui-spritesheet-game.png",
  music: "assets/audio/level-1-simple-bgm.ogg",
  audio: {
    levelTracks: [
      "assets/audio/level-1-simple-bgm.ogg",
      "assets/audio/level-2-electro-loop.ogg",
      "assets/audio/level-3-bluebeat.ogg",
      "assets/audio/level-4-tense-future.ogg",
      "assets/audio/level-5-last-stand.ogg",
    ],
    clear: "assets/audio/clear-winneris.ogg",
    victory: "assets/audio/victory-sting.wav",
    defeat: "assets/audio/defeat-sting.wav",
  },
  finalVideo: "assets/video/final-clear.mp4",
  levelBackgrounds: [
    "assets/optimized/bg-level-1.jpg",
    "assets/optimized/bg-level-2.jpg",
    "assets/optimized/bg-level-3.jpg",
    "assets/optimized/bg-level-4.jpg",
    "assets/optimized/bg-level-5.jpg",
  ],
};

const sprites = {
  player: { x: 8, y: 0, w: 128, h: 140 },
  core: { x: 139, y: 15, w: 84, h: 83 },
  hazard: { x: 257, y: 14, w: 95, h: 84 },
  crystal: { x: 394, y: 13, w: 100, h: 98 },
  mine: { x: 14, y: 134, w: 102, h: 104 },
  gate: { x: 130, y: 132, w: 110, h: 110 },
  shield: { x: 28, y: 244, w: 62, h: 62 },
  heart: { x: 110, y: 250, w: 70, h: 55 },
  flareGold: { x: 27, y: 404, w: 57, h: 50 },
  flareBlue: { x: 110, y: 404, w: 57, h: 50 },
  blast: { x: 24, y: 467, w: 64, h: 44 },
};

const assets = { loaded: false, backgrounds: [], spritesheet: null };

const state = {
  mode: "start",
  levelIndex: 0,
  score: 0,
  lives: 3,
  combo: 0,
  bestCombo: 0,
  energy: 0,
  hits: 0,
  levelStartTime: 0,
  elapsed: 0,
  lastTime: 0,
  hazardTimer: 0,
  coreTimer: 0,
  shardTimer: 0,
  mineTimer: 0,
  gateTimer: 0,
  powerTimer: 0,
  timeRemaining: 0,
  shake: 0,
  flash: 0,
  clearTimer: 0,
  finalGateTimer: 0,
  pointerActive: false,
  joystickActive: false,
  joystickPointerId: null,
  joystickVector: { x: 0, y: 0 },
  stars: [],
  hazards: [],
  mines: [],
  gates: [],
  missiles: [],
  cores: [],
  shards: [],
  powerups: [],
  particles: [],
  drones: [],
  result: null,
  player: { x: 360, y: 1060, radius: 34, targetX: 360, targetY: 1060, invulnerable: 0 },
  missileTimer: 0,
  muted: false,
  shield: 0,
  slowTime: 0,
};
